### ISSUE TITLE
submodule support removed in v2

### ISSUE THREAD

**Issue by lukka** [actions/checkout#133] opened 2020-01-08 18:03 UTC
What is the rationale for the feature removal for a common case?  The advantages of using GitHub Actions is to have some features for free, so that anyone can avoid scripting, and can reuse tested and robust solutions.

**Comment by ericsciple** [comment] 2020-01-18 18:50
good feedback, working on a proposal...

**Comment by marcofranssen** [comment] 2020-01-27 14:24
I tried the submodules approach as mentioned in the README.md

However I need my submodules to work over SSH. Is there something I can try to get the submodule working via SSH.

**Comment by Margen67** [comment] 2020-02-10 05:50
Related: #81

**Comment by chrispat** [comment] 2020-02-13 19:04
Closed as duplicate of #81

**Closed by chrispat** 2020-02-13 19:04 UTC

**Comment by lukka** [comment] 2020-02-13 19:10
this is absolutely not a duplicate of #81. I asked a question, and never got an answer.

**Comment by chrispat** [comment] 2020-02-13 19:37
Both issues are questions about checkout submodules using the v2 version of the action.  Please see https://github.com/actions/checkout/issues/81#issuecomment-585935021 for the answer to your question.
