### ISSUE TITLE
An error occurred during the extraction process in v3

### ISSUE THREAD

**Issue by sr-albert** [actions/checkout#1458] opened 2023-09-05 08:11 UTC
_checkout@v3_

Error: `Can't ***e 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_61ccfa2a-988d-4de6-bd0f-e2fe0b6e63d4/7e8d543b-21a3-4354-8bd9-42048dc2eb3b.tar.gz`

<img width="1614" alt="CleanShot 2023-09-05 at 15 08 05@2x" src="https://github.com/actions/checkout/assets/41714564/0aeb5525-3186-49fc-9a7b-31624a94384b">

**Comment by jeremycopinlm** [comment] 2023-09-05 08:12
same here, it happens sometimes

**Comment by izi-p** [comment] 2023-09-05 08:14
duplicate of https://github.com/actions/checkout/issues/1448

**Closed** 2023-09-05 08:22 UTC
