### ISSUE TITLE
checkout v3 Can't use 'tar -xzf' extract archive file failure

### ISSUE THREAD

**Issue by EgorShtab** [actions/checkout#1450] opened 2023-09-04 14:09 UTC
Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_94a24dc8-c053-41d2-b3f0-4ac6631faceb/42b68b53-d0be-49dd-8ed2-cece4e18ffba.tar.gz. return code: 2.

when using checkout v3

updating to v4 fixes problem

**Comment by patrick-stephens** [comment] 2023-09-04 14:10
Duplicate of #1448 I think

**Comment by relloyd** [comment] 2023-09-04 14:36
Same issue here of course. Because of the way we use this action, I now have hundreds of pipelines broken using v3 and potentially 100s of developers blocked 🤦‍♂️

**Comment by jontrulson** [comment] 2023-09-04 17:41
Same issue for me... I have several CI machines that can no longer check out code.  I cannot update to v4 without some pain, and certainly not soon.

**Comment by ChandlerFerry** [comment] 2023-09-04 21:26
+1

**Comment by nickatnight** [comment] 2023-09-04 21:37
> Same issue for me... I have several CI machines that can no longer check out code. I cannot update to v4 without some pain, and certainly not soon.
> 
> EDIT: Seems to be working again. I restarted the failed jobs and they appear to be running.

Restarting the job worked for me, thanks

**Comment by gaby** [comment] 2023-09-04 21:38
Updating to v4 doesnt fix it for me, same error. https://github.com/gofiber/storage/pull/962

**Comment by CalvinWilkinson** [comment] 2023-09-04 21:39
I as well am having this issue.  So far, when I just re-run the job, it works.  I am updating all of my workflows to _**v4**_ anyway though.  I am currently updating now. If I have any issues with _**v4**_, I will comment here.

**Comment by douglascayers** [comment] 2023-09-04 21:46
Seems related to this issue which has occurred in the past, https://github.com/actions/checkout/issues/673

**Comment by douglascayers** [comment] 2023-09-04 21:50
GitHub Status is reporting a new issue with Actions which may be causing this problem

https://www.githubstatus.com/incidents/tqrmcdmghldw

**Comment by cory-miller** [comment] 2023-10-17 16:06
Closing this issue as it was related to the previously linked incident.

For clarity since there is minimal detail in the link, repository based actions (such as `actions/checkout`) are served through a code caching system which had degraded performance.

**Closed by cory-miller** 2023-10-17 16:06 UTC
