### ISSUE TITLE
"fetch-depth: 0" doesn't fetch all branches

### ISSUE THREAD

**Issue by vitalyk-multinarity** [actions/checkout#1017] opened 2022-11-20 16:01 UTC
I'm using the following snipped for checkout:

```
- name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
```

but when I run 'git branch ' later I see just one branch.
Please suggest,
Thanks,
Vitaly

**Comment by chachako** [comment] 2022-11-27 10:02
same problem

**Comment by edannenberg** [comment] 2022-12-07 09:42
It does fetch all branch data from the remote but doesn't configure any of them locally except the current branch. If you need some other branch you can do so after the checkout action like so:

```
- name: Setup master branch locally without switching current branch
  run: git fetch origin master:master
```

**Comment by marc-hb** [comment] 2022-12-09 22:50
> but when I run 'git branch ' later I see just one branch.

That's because `git branch` shows local branches only. If you run `git branch -a` you will see remote branches too.

See also https://github.com/actions/checkout#checkout-a-different-branch

**Comment by vanZeben** [comment] 2022-12-16 20:12
Hey @vitalyk-multinarity, thank you for your issue :)

I think both @edannenberg and @marc-hb have addressed this issue succinctly (Thank you both for that 🙏🏻), so I'm going to close this issue. If you need more assistance, or there is something that's been missed, please reopen this issue and we can take a look at it :)

**Closed by vanZeben** 2022-12-16 20:12 UTC

**Comment by jarofgreen** [comment] 2025-01-29 18:10
Adding a note about this to https://github.com/actions/checkout?tab=readme-ov-file#Fetch-all-history-for-all-tags-and-branches could be helpful?

**Comment by marc-hb** [comment] 2025-01-29 19:08
I totally forgot I ever commented on this issue...

Here's a very funny, cosmic timing coincidence: if you are one of the 2.5 people interested in such topics and subscribed to this issue, you may be interested in this unexpected git 2.48 "regression" and `git describe` fix I just submitted **yesterday**:
- https://github.com/thesofproject/sof/pull/9801
