### ISSUE TITLE
checkout@v1 does not checkout the forked repo in pull request

### ISSUE THREAD

**Issue by tamalsaha** [actions/checkout#232] opened 2020-05-04 07:17 UTC
An external contributor has opened a pull request to our repo. But it seems that instead of checking out the forked repo, checkout@v1 is cloning the main repo and then fails to find the commit for the pr. See details here: 

- https://github.com/stashed/postgres/runs/642005188?check_suite_focus=true
- https://github.com/stashed/postgres/pull/29/checks?check_run_id=641961152

How do I fix this?

**Comment by riccardoporreca** [comment] 2020-05-04 08:50
Similar issue here:
https://github.com/Milano-R/erum2020-covidr-contest/pull/20/checks?check_run_id=642113150
(not however this is a re-run of a failed job)
```
Checking out the ref
  /usr/bin/git checkout --progress --force -B master refs/remotes/origin/master
  Reset branch 'master'
```
Compare to another pull request using the very same workflow just 2 days ago
https://github.com/Milano-R/erum2020-covidr-contest/pull/17/checks?check_run_id=638697743
```
Checking out the ref
  /usr/bin/git checkout --progress --force refs/remotes/pull/17/merge
  Note: switching to 'refs/remotes/pull/17/merge'.
```
This is potentially very unsafe for workflows using the `refs` to perform **conditional steps on `master`**

**Comment by ericsciple** [comment] 2020-05-05 14:52
@riccardoporreca are you still hitting this issue today? I opened [a fork PR](https://github.com/Milano-R/erum2020-covidr-contest/pull/25/checks?check_run_id=646417731) against your repo but looks like working correctly now. In the github context, ref is correctly showing as "refs/pull/25/merge" now.

**Comment by ericsciple** [comment] 2020-05-05 14:58
@tamalsaha i tested against stashed/postgres too and [appears to be working now](https://github.com/stashed/postgres/pull/31/checks?check_run_id=646455908) too

**Comment by riccardoporreca** [comment] 2020-05-05 15:23
@ericsciple, thanks. I can confirm the issue does not appear any longer for new workflow runs (I have been successfully opening new PRs and did not see it happening any longer).

Re-running the same failed workflow for the PR mentioned above still has the same issue:
https://github.com/Milano-R/erum2020-covidr-contest/pull/15/checks?check_run_id=646513906
but I am confident that this will not occur for new runs

**Comment by tamalsaha** [comment] 2020-05-05 23:06
If the initial CI run fail and then you retry from the GitHub actions UI, does it still work properly?

**Comment by ericsciple** [comment] 2020-05-06 14:32
In this case, i dont think retry will help because the ref name in the payload was wrong. Should work for new fork PRs.

**Comment by riccardoporreca** [comment] 2020-05-18 12:44
@ericsciple, I see this happening in sort of a systematic way, in that re-runs of workflows on PRs get the wrong `refs`.

I have reproduced this with your workflow file in my own fork https://github.com/riccardoporreca/erum2020-covidr-contest/tree/test-gh-context, forcing it to always fail to allow a re-run.

- First run, all OK: https://github.com/Milano-R/erum2020-covidr-contest/pull/51/checks?check_run_id=685261560
  ```
  Run git status
  git status
  shell: /bin/bash -e {0}
  HEAD detached at pull/51/merge
  nothing to commit, working tree clean
  ```
- Re-run: wrong `git status`: https://github.com/Milano-R/erum2020-covidr-contest/pull/51/checks?check_run_id=685263413
  ```
  Run git status
  git status
  shell: /bin/bash -e {0}
  On branch test-gh-context
  Your branch is up to date with 'origin/test-gh-context'.
  ```

I know there are also issues with the `cache` actions on PRs upon re-runs, see https://github.com/actions/cache/issues/208#issuecomment-596664572. Perhaps the root cause is the same.

Hope this helps.

**Comment by ericsciple** [comment] 2020-05-18 22:45
@riccardoporreca thanks! Good find. I was able to locate the corresponding issue internally... looks like it's being worked on.

**Comment by riccardoporreca** [comment] 2020-05-19 16:31
Working like a charm now (https://github.com/actions/cache/issues/208#issuecomment-630896455)
 https://github.com/Milano-R/erum2020-covidr-contest/pull/51/checks?check_run_id=689705978

**Comment by ericsciple** [comment] 2020-05-27 22:04
Sounds like the two issues are fixed now. Let me know or reopen if otherwise

**Closed by ericsciple** 2020-05-27 22:04 UTC
