### ISSUE TITLE
checkout@v3 checks out submodule at wrong revision.

### ISSUE THREAD

**Issue by ingomueller-net** [actions/checkout#1271] opened 2023-04-03 16:35 UTC
I have a build job that keeps failing because the `actions/checkout@v3` seems to keep checking out the wrong revision of a submodule.

One failed build job is [this one](https://github.com/iree-org/iree-llvm-sandbox/actions/runs/4598917944/jobs/8123624071?pr=672). It says:

```
HEAD is now at be30410 Merge b6a3dc3808e339a15b219d24a8c60e927816b8ef into fd2dd860a809499994a6220d6e18b4667e6e27f5
```

and later

```
Submodule path 'experimental/iterators/third_party/llvm-project': checked out '4e563616a5fffa1204286a9aa03604a68a7db835'
```

However, the [submodule at revision `b6a3dc3808e339a15b219d24a8c60e927816b8ef `](https://github.com/iree-org/iree-llvm-sandbox/tree/b6a3dc3808e339a15b219d24a8c60e927816b8ef/experimental/iterators/third_party) points to `cf115f30bb36ee67b345426911c1396cef9164e4`, not `4e563616a5fffa1204286a9aa03604a68a7db835`.

What is remarkable is that the same commit (`b6a3dc3808e339a15b219d24a8c60e927816b8ef`) has run successfully [a few days ago](https://github.com/iree-org/iree-llvm-sandbox/actions/runs/4573126685/jobs/8073176012).

Any ideas how to fix this?

**Comment by jww3** [comment] 2023-04-03 17:40
Duplicate of https://github.com/actions/checkout/issues/1262 ?

**Comment by ingomueller-net** [comment] 2023-04-04 10:04
> Duplicate of #1262 ?

Not impossible but it doesn't seem to be the same symptom: In my case, the correct top-level repository is checked out whereas in #1262 that doesn't seem to be the case. Instead, in my case, a submodule is checked out in the wrong version.

**Comment by jww3** [comment] 2023-04-05 18:29
I notice I see the same behavior when I try to clone the repo locally.  Can you please double-check that the submodules are configured correctly.

```
$ git clone https://github.com/iree-org/iree-llvm-sandbox.git --depth 1500
$ cd iree-llvm-sandbox/
$ git submodule
  -4e563616a5fffa1204286a9aa03604a68a7db835 experimental/iterators/third_party/llvm-project
  -853dd6ead922cc0115beddc3d74b88af8b437172 third_party/iree

$ git submodule init
Submodule 'experimental/iterators/third_party/llvm-project' (https://github.com/llvm/llvm-project.git) registered for path 'experimental/iterators/third_party/llvm-project'
Submodule 'third_party/iree' (https://github.com/google/iree.git) registered for path 'third_party/iree'

$ git submodule
-4e563616a5fffa1204286a9aa03604a68a7db835 experimental/iterators/third_party/llvm-project
-853dd6ead922cc0115beddc3d74b88af8b437172 third_party/iree

$ git submodule update
Cloning into '/workspaces/iree-llvm-sandbox/experimental/iterators/third_party/llvm-project'...
Cloning into '/workspaces/iree-llvm-sandbox/third_party/iree'...
Submodule path 'experimental/iterators/third_party/llvm-project': checked out '4e563616a5fffa1204286a9aa03604a68a7db835'
Submodule path 'third_party/iree': checked out '853dd6ead922cc0115beddc3d74b88af8b437172'

$ git submodule
 4e563616a5fffa1204286a9aa03604a68a7db835 experimental/iterators/third_party/llvm-project
 (llvmorg-17-init-6626-g4e563616a5ff)
 853dd6ead922cc0115beddc3d74b88af8b437172 third_party/iree (candidate-20220901.253-3-g853dd6ead)
```

**Comment by ingomueller-net** [comment] 2023-04-06 10:37
Your commands run on `main` (presumable `fd2dd86`), right? At that point, the `experimental/iterators/third_party/llvm-project` submodule indeed pointed to `4e563616a5` (see [here](https://github.com/iree-org/iree-llvm-sandbox/tree/fd2dd860a809499994a6220d6e18b4667e6e27f5/experimental/iterators/third_party)), so your behavior locally is consistent with what one would expect.

However, on the build that breaks, which runs against commit `b6a3dc3808e` of the main repo, the submodule at the same path points to version `cf115f3` (see [here](https://github.com/iree-org/iree-llvm-sandbox/tree/b6a3dc3808e339a15b219d24a8c60e927816b8ef/experimental/iterators/third_party)); however, the version `4e563616a5f` is checked out (see [here](https://github.com/iree-org/iree-llvm-sandbox/actions/runs/4598917944/jobs/8123624071?pr=672) under "Checkout projects", then "Fetching submodules"). That is in contrary what I would expect!

I have since then rebased the PRs and stop having the problem, so this issues isn't urgent for me anymore. However, unless I am really misreading something, it seems like the wrong submodule was checked out.

**Comment by jww3** [comment] 2023-04-06 15:51
I see what you're saying.  I get the expected behavior when I sync the super repo to an older commit.

(`b6a3dc3808e` seems to be gone at this point -- likely due to your rebase? 

   When I [navigate to b6a3dc3808e](https://github.com/iree-org/iree-llvm-sandbox/commit/b6a3dc3808e339a15b219d24a8c60e927816b8ef), I see the following warning:

```
This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
```
)

Keep in mind that when a GitHub Actions workflow runs in the context of validating a Pull Request (i.e. `on: pull_request` ), it runs neither against the development branch nor against the destination branch.  Rather, it runs on a pseudo-branch that represents a merge of the two.

This is documented briefly here:  https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request

> Note that GITHUB_SHA for this event is the last merge commit of the pull request merge branch.

(The "pull request merge branch" is the "pseudo-branch" I'm referring to.)

More explanation is offered here:  https://github.com/orgs/community/discussions/25367#discussioncomment-3247664

and [this Stackoverflow post](https://stackoverflow.com/a/68068674) has a good summary.

My guess is that:  in your case, the `main` branch moved forward while your PR was under review and this is why you saw the change in behavior in the PR validation.  When the submodule commit updates from `main` landed on the pseudo-branch, suddenly you started seeing new errors.  

I've seen this myself in my work when breaking changes are introduced on the `main` branch.  You stop and scratch your head for a moment because the code compiles fine in your dev branch and compiles fine on `main` and yet your PR validation is failing with an error you're unable to reproduce.

Also, note that significant time can pass from when the breaking changes are introduced on the destination branch and the time they show up in PR validation.  This is because, by default, an update to the destination branch won't trigger a re-run of the PR validations.  Generally, only a change to the development branch will trigger PR validation to be re-run.

**Comment by jww3** [comment] 2023-05-02 20:22
Feel free to reopen if the above explanation isn't helpful.

**Closed by jww3** 2023-05-02 20:22 UTC
